apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-canary
  namespace: shopmicro
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  rules:
  - host: shopmicro.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-v2
            port:
              number: 8080
