apiVersion: v1
kind: ConfigMap
metadata:
  name: shopmicro-config
  namespace: shopmicro
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: shopmicro
  DB_USER: postgres
  REDIS_URL: redis://redis:6379
