apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: shopmicro-frontend:local
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_BASE
              value: http://backend:8080
            - name: VITE_ML_BASE
              value: http://ml-service:5000
          resources:
            requests: { cpu: "50m", memory: "96Mi" }
            limits: { cpu: "300m", memory: "192Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shopmicro
spec:
  selector: { app: frontend }
  ports:
    - port: 3000
      targetPort: 3000
