apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels: { app: ml-service }
  template:
    metadata:
      labels: { app: ml-service }
    spec:
      containers:
        - name: ml-service
          image: shopmicro-ml:local
          ports:
            - containerPort: 5000
          env:
            - name: OTEL_ENABLED
              value: "false"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests: { cpu: "50m", memory: "96Mi" }
            limits: { cpu: "300m", memory: "192Mi" }
          readinessProbe:
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: shopmicro
spec:
  selector: { app: ml-service }
  ports:
    - port: 5000
      targetPort: 5000
